# Generated by Django 3.2.14 on 2022-09-15 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depart',
            options={'verbose_name': 'Цех', 'verbose_name_plural': 'Цеха'},
        ),
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name': 'Смена с', 'verbose_name_plural': 'Смены с'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-autodate'], 'verbose_name': 'Запись с шапкой', 'verbose_name_plural': 'Записи с шапкой'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['pub_time'], 'verbose_name': 'Запись в смене', 'verbose_name_plural': 'Записи в смене'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользлователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Вахта №', 'verbose_name_plural': 'Вахты №'},
        ),
        migrations.AddField(
            model_name='record',
            name='workers',
            field=models.ManyToManyField(related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
