# Generated by Django 3.2.14 on 2022-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='watch',
            field=models.CharField(choices=[('Вахта 1', '1'), ('Вахта 2', '2'), ('Вахта 3', '3'), ('Вахта 4', '4'), ('Вахта 5', '5')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
