# Generated by Django 3.2.14 on 2022-08-27 16:54

from django.db import migrations, models
import django.db.models.deletion
import log.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['pub_time']},
        ),
        migrations.RemoveField(
            model_name='text',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='text',
            name='pub_time',
            field=models.TimeField(default=log.models.get_time, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='text',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='log.record', verbose_name='Записи смены'),
        ),
    ]
