# Generated by Django 3.2.14 on 2022-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_record_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='duty_time',
            field=models.CharField(choices=[('0-8', '0-8'), ('8-16', '8-16'), ('16-24', '16-24')], default=-8, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='watch',
            field=models.CharField(choices=[('0-8', '0-8'), ('8-16', '8-16'), ('16-24', '16-24')], max_length=7),
        ),
    ]
