# Generated by Django 3.2.14 on 2022-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20220730_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='watch',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=7),
        ),
    ]
