# Generated by Django 3.2.14 on 2022-08-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_record_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='duty_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='log.duty'),
        ),
        migrations.AlterField(
            model_name='record',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='log.watch'),
        ),
    ]
